name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: set domain suffix
        id: domain
        ## This will become a custom domain like zero.zenmo.com
        run: echo "DOMAIN_SUFFIX=thankfulbay-feb62349.westeurope.azurecontainerapps.io" >> $GITHUB_OUTPUT
      - if: github.event_name == 'pull_request'
        id: image-tag
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const commit = context.payload.pull_request?.head?.sha ?? context.sha
            const shortCommit = commit.substr(0, 7)
            const branch = context.payload.pull_request?.head?.ref ?? context.ref.match(/refs\/heads\/(.+)/)[1]
            // Azure Container Apps name can be max 32 characters
            const maxBranchLength = 32 - shortCommit.length - 'kleinverbruik'.length - 2 * '-'.length
            const shortBranch = branch.substr(0, maxBranchLength)
            
            return shortBranch + '-' + shortCommit
      - if: github.event_name == 'pull_request'
        name: set KLEINVERBRUIK_URL for pull request test environment
        run: echo "KLEINVERBRUIK_URL=https://kleinverbruik-${{ steps.image-tag.outputs.result }}.${{ steps.domain.outputs.DOMAIN_SUFFIX }}" >> $GITHUB_ENV
      - if: github.event_name == 'push'
        name: set KLEINVERBRUIK_URL for main application
        run: echo "KLEINVERBRUIK_URL=https://kleinverbruik.${{ steps.domain.outputs.DOMAIN_SUFFIX }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Npm install
        working-directory: frontend
        run: npm ci
      - name: Type check
        working-directory: frontend
        run: npx tsc
      - name: Test
        working-directory: frontend
        run: npm test
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_HILL_0E1D72903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_HILL_0E1D72903 }}
          action: "close"
